// GAMES — one line per entry
const CATS = {"game": "GAME"};
const RAW = [
  {slug:"meme-sound-generator",name:"Meme Sound Generator",cat:"game",blurb:"A soundboard of 25 sounds, all synthesised live in your browser with Web Audio.",tags:["SOUNDBOARD","WEB AUDIO"],ready:true},
  {slug:"snake",name:"Snake",cat:"game",blurb:"Classic snake on canvas. Arrows, WASD or swipe.",tags:["ARCADE"],ready:true},
  {slug:"tic-tac-toe",name:"Tic-Tac-Toe",cat:"game",blurb:"A minimax opponent that does not let you win.",tags:["MINIMAX"],ready:true},
  {slug:"memory-match",name:"Memory Match",cat:"game",blurb:"Flip and pair. Tracks your best move count.",tags:["MEMORY"],ready:true},
  {slug:"2048",name:"2048",cat:"game",blurb:"Merge the tiles and chase 2048.",tags:["PUZZLE"],ready:true},
  {slug:"wordle",name:"Word Guess",cat:"game",blurb:"Six guesses, colour-coded feedback, saved streaks.",tags:["WORDS"],ready:true},
  {slug:"minesweeper",name:"Minesweeper",cat:"game",blurb:"Flag the mines, clear the field, three difficulties.",tags:["PUZZLE"],ready:true},
  {slug:"typing-race",name:"Typing Race",cat:"game",blurb:"Beat the clock against a moving target pace.",tags:["SPEED"],ready:true},
  {slug:"chess",name:"Chess",cat:"game",blurb:"Two-player board with check, checkmate and a live ELO rating.",tags:["BOARD","ELO"],ready:true},
  {slug:"checkers",name:"Checkers",cat:"game",blurb:"Draughts with forced captures, kings and a simple AI.",tags:["BOARD","AI"],ready:true},
  {slug:"reversi",name:"Reversi / Othello",cat:"game",blurb:"Flip discs in every direction against a scoring AI.",tags:["BOARD","FLIP"],ready:true},
  {slug:"connect-four",name:"Connect Four",cat:"game",blurb:"Drop discs, four in a row, AI that blocks.",tags:["AI","PUZZLE"],ready:true},
  {slug:"simon",name:"Simon Says",cat:"game",blurb:"Repeat the growing sequence — each pad has its own tone.",tags:["MEMORY","AUDIO"],ready:true},
  {slug:"mastermind",name:"Mastermind",cat:"game",blurb:"Crack the four-colour code with exact/partial feedback.",tags:["LOGIC","PUZZLE"],ready:true},
  {slug:"hangman",name:"Hangman",cat:"game",blurb:"Guess the word before the drawing runs out.",tags:["WORDS","GUESS"],ready:true},
  {slug:"falling-sand",name:"Sandbox",cat:"game",blurb:"27 elements, density physics and real pair reactions — pour, ignite, dissolve, grow.",tags:["SANDBOX","SIM","PHYSICS"],ready:true},
  {slug:"circle-score",name:"Circle Score",cat:"game",blurb:"Draw one freehand circle and get scored on how round it really is.",tags:["SKILL","CANVAS"],ready:true},
  {slug:"password-gauntlet",name:"Password Gauntlet",cat:"game",blurb:"Every rule you satisfy unlocks a worse one. Ten rules stand between you and the win.",tags:["PUZZLE","RULES"],ready:true},
  {slug:"spend-a-billion",name:"Billion-Dollar Budget",cat:"game",blurb:"You have one billion dollars. Try to actually spend it.",tags:["TYCOON","BUDGET"],ready:true},
  {slug:"deep-descent",name:"Deep Descent",cat:"game",blurb:"Scroll from the surface to the Challenger Deep, 10,994 metres down.",tags:["EXPLORE","OCEAN"],ready:true},
  {slug:"life-in-numbers",name:"Life in Numbers",cat:"game",blurb:"Your heartbeats, breaths and kilometres travelled around the Sun so far.",tags:["NUMBERS","FUN"],ready:true},
  {slug:"battleship",name:"Battleship",cat:"game",blurb:"Sink the whole fleet. The AI hunts with real targeting logic, not luck.",tags:["GAMES","STRATEGY","AI"],ready:true},
  {slug:"breakout",name:"Breakout",cat:"game",blurb:"Bricks, lives and power-ups, with the pace ramping as you clear them.",tags:["GAMES","ARCADE"],ready:true},
  {slug:"pong",name:"Pong",cat:"game",blurb:"Classic rally against an AI paddle that tracks the ball.",tags:["GAMES","ARCADE"],ready:true},
  {slug:"sudoku",name:"Sudoku",cat:"game",blurb:"Three difficulties, pencil notes, and a unique-solution generator.",tags:["GAMES","PUZZLE","LOGIC"],ready:true},
  {slug:"tetris",name:"Tetris",cat:"game",blurb:"Seven-bag randomiser, hold piece, next queue and rising speed.",tags:["GAMES","ARCADE","PUZZLE"],ready:true},
  {slug:"sandbox-3d",name:"Sandbox 3D",cat:"game",blurb:"A real 3D voxel world of 92,160 cubes. Paint sand, water, lava and fire and watch density physics run.",tags:["GAMES","3D","VOXELS","PHYSICS"],ready:true},
  {slug:"asteroids",name:"Asteroids",cat:"game",blurb:"Thrust, rotate, drift and split rocks with real inertia.",tags:["GAMES","ARCADE"],ready:true},
  {slug:"flappy-bird",name:"Flappy Bird",cat:"game",blurb:"Thread the gaps. Your best score is saved on this device.",tags:["GAMES","ARCADE"],ready:true},
  {slug:"gomoku",name:"Gomoku",cat:"game",blurb:"Five in a row against an AI that scores every candidate move.",tags:["GAMES","STRATEGY","AI"],ready:true},
  {slug:"nim",name:"Nim",cat:"game",blurb:"Two piles, optimal play. The AI always leaves you a losing position.",tags:["GAMES","STRATEGY","MATH"],ready:true},
  {slug:"space-invaders",name:"Space Invaders",cat:"game",blurb:"Descending waves, destructible shields and a rising score.",tags:["GAMES","ARCADE"],ready:true},
  {slug:"jepa-lab",name:"Latent Physics Lab",cat:"game",blurb:"A JEPA learns to predict a ball's next position from a latent representation of a frame - never from pixels. It trains in your browser.",tags:["GAMES","AI","ML"],ready:true},
  {slug:"n-body-orbits",name:"N-Body Orbits",cat:"game",blurb:"Real Newtonian gravity at the real G. Start circular, nudge the planet, and watch the ellipse appear - with live semi-major axis, eccentricity and period.",tags:["GAMES","PHYSICS","SIMULATION","ASTROPHYSICS"],ready:true},
  {slug:"pendulum-lab",name:"Pendulum Lab",cat:"game",blurb:"Nine coupled pendulums on a real g = 9.81. Small-angle period printed underneath; the chaos beside it is the point.",tags:["GAMES","PHYSICS","SIMULATION","MATH"],ready:true},
  {slug:"reaction-diffusion",name:"Reaction Diffusion",cat:"game",blurb:"A real Gray-Scott solver. Eight regimes - mitosis, coral, worms, solitons, fingerprint - and the feed/kill map that makes them.",tags:["GAMES","SIMULATION","PHYSICS","VISUAL"],ready:true},
  {slug:"wave-equation",name:"Wave Equation",cat:"game",blurb:"An explicit leapfrog finite-difference solver. Resonance, standing waves and superposition, with the measured period next to the theory.",tags:["GAMES","SIMULATION","PHYSICS","MATH"],ready:true},
  {slug:"fruit-slice",name:"Fruit Slice",cat:"game",blurb:"Fruit Slice - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"fruit-slice",name:"Fruit Slice",cat:"game",blurb:"Fruit Slice - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"lane-runner",name:"Lane Runner",cat:"game",blurb:"Lane Runner - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"lane-runner",name:"Lane Runner",cat:"game",blurb:"Lane Runner - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"mole-mash",name:"Mole Mash",cat:"game",blurb:"Mole Mash - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"mole-mash",name:"Mole Mash",cat:"game",blurb:"Mole Mash - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"slingshot-siege",name:"Slingshot Siege",cat:"game",blurb:"Slingshot Siege - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"slingshot-siege",name:"Slingshot Siege",cat:"game",blurb:"Slingshot Siege - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"tower-stack",name:"Tower Stack",cat:"game",blurb:"Tower Stack - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"tower-stack",name:"Tower Stack",cat:"game",blurb:"Tower Stack - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"tron-arena",name:"Tron Arena",cat:"game",blurb:"Tron Arena - playable in the browser.",tags:["GAMES"],ready:true},
  {slug:"tron-arena",name:"Tron Arena",cat:"game",blurb:"Tron Arena - playable in the browser.",tags:["GAMES"],ready:true},
];
