// GAMES — one line per entry
const CATS = {"game": "GAME"};
const RAW = [
  {slug:"meme-sound-generator",name:"Meme Sound Generator",cat:"game",blurb:"A soundboard of 25 sounds, all synthesised live in your browser with Web Audio.",tags:["SOUNDBOARD","WEB AUDIO"],ready:true},
  {slug:"snake",name:"Snake",cat:"game",blurb:"Classic snake on canvas. Arrows, WASD or swipe.",tags:["ARCADE"],ready:true},
  {slug:"tic-tac-toe",name:"Tic-Tac-Toe",cat:"game",blurb:"A minimax opponent that does not let you win.",tags:["MINIMAX"],ready:true},
  {slug:"memory-match",name:"Memory Match",cat:"game",blurb:"Flip and pair. Tracks your best move count.",tags:["MEMORY"],ready:true},
  {slug:"2048",name:"2048",cat:"game",blurb:"Merge the tiles and chase 2048.",tags:["PUZZLE"],ready:true},
  {slug:"wordle",name:"Word Guess",cat:"game",blurb:"Six guesses, colour-coded feedback, saved streaks.",tags:["WORDS"],ready:true},
  {slug:"minesweeper",name:"Minesweeper",cat:"game",blurb:"Flag the mines, clear the field, three difficulties.",tags:["PUZZLE"],ready:true},
  {slug:"typing-race",name:"Typing Race",cat:"game",blurb:"Beat the clock against a moving target pace.",tags:["SPEED"],ready:true},
  {slug:"chess",name:"Chess",cat:"game",blurb:"Two-player board with check, checkmate and a live ELO rating.",tags:["BOARD","ELO"],ready:true},
  {slug:"checkers",name:"Checkers",cat:"game",blurb:"Draughts with forced captures, kings and a simple AI.",tags:["BOARD","AI"],ready:true},
  {slug:"reversi",name:"Reversi / Othello",cat:"game",blurb:"Flip discs in every direction against a scoring AI.",tags:["BOARD","FLIP"],ready:true},
  {slug:"connect-four",name:"Connect Four",cat:"game",blurb:"Drop discs, four in a row, AI that blocks.",tags:["AI","PUZZLE"],ready:true},
  {slug:"simon",name:"Simon Says",cat:"game",blurb:"Repeat the growing sequence — each pad has its own tone.",tags:["MEMORY","AUDIO"],ready:true},
  {slug:"mastermind",name:"Mastermind",cat:"game",blurb:"Crack the four-colour code with exact/partial feedback.",tags:["LOGIC","PUZZLE"],ready:true},
  {slug:"hangman",name:"Hangman",cat:"game",blurb:"Guess the word before the drawing runs out.",tags:["WORDS","GUESS"],ready:true},
  {slug:"falling-sand",name:"Sandbox",cat:"game",blurb:"27 elements, density physics and real pair reactions — pour, ignite, dissolve, grow.",tags:["SANDBOX","SIM","PHYSICS"],ready:true},
  {slug:"circle-score",name:"Circle Score",cat:"game",blurb:"Draw one freehand circle and get scored on how round it really is.",tags:["SKILL","CANVAS"],ready:true},
  {slug:"password-gauntlet",name:"Password Gauntlet",cat:"game",blurb:"Every rule you satisfy unlocks a worse one. Ten rules stand between you and the win.",tags:["PUZZLE","RULES"],ready:true},
  {slug:"spend-a-billion",name:"Billion-Dollar Budget",cat:"game",blurb:"You have one billion dollars. Try to actually spend it.",tags:["TYCOON","BUDGET"],ready:true},
  {slug:"deep-descent",name:"Deep Descent",cat:"game",blurb:"Scroll from the surface to the Challenger Deep, 10,994 metres down.",tags:["EXPLORE","OCEAN"],ready:true},
  {slug:"life-in-numbers",name:"Life in Numbers",cat:"game",blurb:"Your heartbeats, breaths and kilometres travelled around the Sun so far.",tags:["NUMBERS","FUN"],ready:true},
];
