// TOOLS — one line per entry
const CATS = {"data": "DATA & CODE", "document": "PDF & DOCS", "audio": "AUDIO & SPEECH", "design": "DESIGN & COLOUR", "math": "MATH & CONVERSION", "web": "NETWORK & WEB", "study": "STUDY & CAREER"};
const RAW = [
  {slug:"json-formatter",name:"JSON Prettifier",cat:"data",blurb:"Format, minify and validate JSON with a live error pointer.",tags:["JSON","CLIENT-SIDE"],ready:true},
  {slug:"base64",name:"Base64 Encoder",cat:"data",blurb:"Encode and decode Base64 text or files, UTF-8 safe.",tags:["BASE64","CLIENT-SIDE"],ready:true},
  {slug:"url-encoder",name:"URL Encoder",cat:"data",blurb:"Percent-encode and decode URL components and query strings.",tags:["URI","CLIENT-SIDE"],ready:true},
  {slug:"case-converter",name:"String Case Converter",cat:"data",blurb:"UPPER, lower, Title, camel, snake and kebab in one pass.",tags:["TEXT","CLIENT-SIDE"],ready:true},
  {slug:"word-counter",name:"Character & Word Counter",cat:"data",blurb:"Words, characters, lines, reading time as you type.",tags:["TEXT","CLIENT-SIDE"],ready:true},
  {slug:"uuid-generator",name:"UUID Generator",cat:"data",blurb:"Bulk v4 UUIDs from crypto.randomUUID, one click to copy.",tags:["UUID","CLIENT-SIDE"],ready:true},
  {slug:"hash-generator",name:"Hash Generator",cat:"data",blurb:"SHA-256, SHA-384 and SHA-512 via the Web Crypto API.",tags:["SHA","CRYPTO"],ready:true},
  {slug:"timestamp",name:"Epoch Converter",cat:"data",blurb:"Unix timestamps to dates and back, live in both directions.",tags:["TIME","CLIENT-SIDE"],ready:true},
  {slug:"binary-hex",name:"Binary / Hex / Octal",cat:"data",blurb:"Convert numbers between bases with a live bit view.",tags:["MATH","CLIENT-SIDE"],ready:true},
  {slug:"color-converter",name:"HEX / RGB / HSL",cat:"data",blurb:"Convert colours three ways with a live preview.",tags:["COLOUR","CLIENT-SIDE"],ready:true},
  {slug:"password-generator",name:"Password Generator",cat:"data",blurb:"Strong random passwords from crypto.getRandomValues.",tags:["SECURITY","CRYPTO"],ready:true},
  {slug:"qr-generator",name:"QR Code Generator",cat:"web",blurb:"Generate QR codes for links, text or Wi-Fi.",tags:["QR","CLIENT-SIDE"],ready:true},
  {slug:"ip-inspector",name:"IP & UA Inspector",cat:"web",blurb:"Your public IP, user agent and screen facts.",tags:["NETWORK","CLIENT-SIDE"],ready:true},
  {slug:"markdown-preview",name:"Markdown Previewer",cat:"data",blurb:"Live Markdown preview rendered in the browser.",tags:["MARKDOWN"],ready:true},
  {slug:"csv-json",name:"CSV to JSON",cat:"data",blurb:"Convert delimited text and JSON both ways.",tags:["CSV","JSON"],ready:true},
  {slug:"html-entities",name:"HTML Entity Escaper",cat:"data",blurb:"Escape and unescape HTML and XML entities safely.",tags:["HTML","XML"],ready:true},
  {slug:"jwt-debugger",name:"JWT Debugger",cat:"data",blurb:"Decode a JWT header and payload, client-side only.",tags:["JWT"],ready:true},
  {slug:"diff-checker",name:"Diff Checker",cat:"data",blurb:"Compare two blocks of text line by line.",tags:["DIFF"],ready:true},
  {slug:"lorem-ipsum",name:"Lorem Ipsum Generator",cat:"data",blurb:"Placeholder paragraphs, sentences or words.",tags:["TEXT"],ready:true},
  {slug:"regex-tester",name:"Regex Tester",cat:"data",blurb:"Test patterns with live match highlighting.",tags:["REGEX"],ready:true},
  {slug:"sql-formatter",name:"SQL Formatter",cat:"data",blurb:"Reindent SQL queries so they can actually be read.",tags:["SQL"],ready:true},
  {slug:"pdf-viewer",name:"PDF Viewer",cat:"document",blurb:"Open a PDF in the browser and inspect page by page.",tags:["PDF"],ready:true},
  {slug:"image-to-pdf",name:"Image to PDF",cat:"document",blurb:"Combine images into a single PDF, in your order.",tags:["PDF"],ready:true},
  {slug:"pdf-splitter",name:"PDF Splitter",cat:"document",blurb:"Extract or drop pages and download the result.",tags:["PDF"],ready:true},
  {slug:"pdf-to-text",name:"PDF to Text",cat:"document",blurb:"Pull the text layer out of any PDF.",tags:["PDF"],ready:true},
  {slug:"tts",name:"Browser TTS",cat:"audio",blurb:"Read text aloud with the voices on your device.",tags:["SPEECH"],ready:true},
  {slug:"voice-recorder",name:"Voice Recorder",cat:"audio",blurb:"Record, trim and download clips locally.",tags:["MIC"],ready:true},
  {slug:"tone-synth",name:"Tone & SFX Synth",cat:"audio",blurb:"Generate tones and effects with the Web Audio API.",tags:["AUDIO"],ready:true},
  {slug:"pitch-speed",name:"Pitch & Speed Changer",cat:"audio",blurb:"Shift pitch and playback rate of any audio file.",tags:["AUDIO"],ready:true},
  {slug:"password-strength",name:"Password Analyser",cat:"data",blurb:"Entropy, crack-time estimates and weakness checks.",tags:["SECURITY"],ready:true},
  {slug:"gradient-maker",name:"CSS Gradient Maker",cat:"design",blurb:"Build linear and radial gradients, copy the CSS.",tags:["CSS"],ready:true},
  {slug:"box-shadow",name:"Box Shadow Generator",cat:"design",blurb:"Layer shadows visually and copy the CSS.",tags:["CSS"],ready:true},
  {slug:"palette",name:"Palette Extractor",cat:"design",blurb:"Pull a palette out of any image you drop in.",tags:["COLOUR"],ready:true},
  {slug:"favicon-generator",name:"Favicon Generator",cat:"design",blurb:"Resize an image to every favicon size and zip it.",tags:["ICONS"],ready:true},
  {slug:"unit-converter",name:"Unit Converter",cat:"math",blurb:"Length, mass, temperature, data and more.",tags:["UNITS"],ready:true},
  {slug:"calculator",name:"Scientific Calculator",cat:"math",blurb:"Full expression evaluation in the browser.",tags:["MATH"],ready:true},
  {slug:"aspect-ratio",name:"Aspect Ratio Calculator",cat:"math",blurb:"Fit widths and heights at any ratio.",tags:["MATH"],ready:true},
  {slug:"loan-calc",name:"Loan & Interest Simulator",cat:"math",blurb:"Compound interest and repayment schedules, charted.",tags:["FINANCE"],ready:true},
  {slug:"bmi",name:"BMI Calculator",cat:"math",blurb:"Body mass index with healthy-range context.",tags:["HEALTH"],ready:true},
  {slug:"gpa",name:"GPA Calculator",cat:"math",blurb:"Semester GPA from your grades and credit units.",tags:["SCHOOL"],ready:true},
  {slug:"meta-tags",name:"Meta Tag Generator",cat:"web",blurb:"Open Graph and Twitter card tags from a form.",tags:["SEO"],ready:true},
  {slug:"http-status",name:"HTTP Status Reference",cat:"web",blurb:"Every status code, searchable, with plain-English notes.",tags:["HTTP"],ready:true},
  {slug:"robots-sitemap",name:"Robots & Sitemap Generator",cat:"web",blurb:"Generate robots.txt and a sitemap skeleton.",tags:["SEO"],ready:true},
  {slug:"flashcards",name:"Flashcards",cat:"study",blurb:"Spaced-repetition decks that live in your browser.",tags:["STUDY"],ready:true},
  {slug:"citation-generator",name:"Citation Generator",cat:"study",blurb:"APA, MLA and Harvard references from a source.",tags:["STUDY"],ready:true},
  {slug:"resume-formatter",name:"Resume Formatter",cat:"study",blurb:"Plain text CV in, styled PDF out.",tags:["CAREER"],ready:true},
  {slug:"typing-speed",name:"Typing Speed Test",cat:"study",blurb:"WPM and accuracy over a timed passage.",tags:["TEST"],ready:true},
  {slug:"pomodoro",name:"Pomodoro Timer",cat:"study",blurb:"Focus sessions with a chime, right in the tab.",tags:["FOCUS"],ready:true},
  {slug:"kanban",name:"Kanban Board",cat:"study",blurb:"Drag-and-drop tasks saved in this browser.",tags:["TASKS"],ready:true},
    {slug:"background-remover",name:"Background Remover",cat:"design",blurb:"Cut the background off a photo in your browser — no upload, no watermark.",tags:["IMAGE","PNG"],ready:true},
    {slug:"element-mixer",name:"Element Mixer",cat:"study",blurb:"All 118 elements — tap two to see the compound they form.",tags:["CHEMISTRY","TABLE"],ready:true},
  {slug:"pdf-to-word",name:"PDF to Word",cat:"document",blurb:"Extract text from any PDF into a Word-compatible .doc download.",tags:["PDF","WORD"],ready:true},
  {slug:"word-to-pdf",name:"Word to PDF",cat:"document",blurb:"Paste text, pick a page size, export a clean paginated PDF.",tags:["PDF","EXPORT"],ready:true},
  {slug:"merge-pdf",name:"Merge PDF",cat:"document",blurb:"Join several PDFs in your chosen order, download one file.",tags:["PDF","MERGE"],ready:true},
  {slug:"split-pdf",name:"Split PDF",cat:"document",blurb:"Split every N pages or by custom ranges, download each part.",tags:["PDF","SPLIT"],ready:true},
  {slug:"organize-pdf",name:"Organise PDF Pages",cat:"document",blurb:"Delete, rotate and reorder pages, then download the result.",tags:["PDF","ROTATE"],ready:true},
  {slug:"compress-pdf",name:"Compress PDF",cat:"document",blurb:"Re-save with object streams and show before/after file size.",tags:["PDF","COMPRESS"],ready:true},
  ];