// TOOLS — one line per entry
const CATS = {"data": "DATA & CODE", "document": "PDF & DOCS", "audio": "AUDIO & SPEECH", "design": "DESIGN & COLOUR", "math": "MATH & CONVERSION", "web": "NETWORK & WEB", "study": "STUDY & CAREER", "text": "WRITING & TEXT"};
const RAW = [
  {slug:"json-formatter",name:"JSON Prettifier",cat:"data",blurb:"Format, minify and validate JSON with a live error pointer.",tags:["JSON","CLIENT-SIDE"],ready:true},
  {slug:"base64",name:"Base64 Encoder",cat:"data",blurb:"Encode and decode Base64 text or files, UTF-8 safe.",tags:["BASE64","CLIENT-SIDE"],ready:true},
  {slug:"url-encoder",name:"URL Encoder",cat:"data",blurb:"Percent-encode and decode URL components and query strings.",tags:["URI","CLIENT-SIDE"],ready:true},
  {slug:"case-converter",name:"String Case Converter",cat:"data",blurb:"UPPER, lower, Title, camel, snake and kebab in one pass.",tags:["TEXT","CLIENT-SIDE"],ready:true},
  {slug:"word-counter",name:"Character & Word Counter",cat:"data",blurb:"Words, characters, lines, reading time as you type.",tags:["TEXT","CLIENT-SIDE"],ready:true},
  {slug:"uuid-generator",name:"UUID Generator",cat:"data",blurb:"Bulk v4 UUIDs from crypto.randomUUID, one click to copy.",tags:["UUID","CLIENT-SIDE"],ready:true},
  {slug:"hash-generator",name:"Hash Generator",cat:"data",blurb:"SHA-256, SHA-384 and SHA-512 via the Web Crypto API.",tags:["SHA","CRYPTO"],ready:true},
  {slug:"timestamp",name:"Epoch Converter",cat:"data",blurb:"Unix timestamps to dates and back, live in both directions.",tags:["TIME","CLIENT-SIDE"],ready:true},
  {slug:"binary-hex",name:"Binary / Hex / Octal",cat:"data",blurb:"Convert numbers between bases with a live bit view.",tags:["MATH","CLIENT-SIDE"],ready:true},
  {slug:"color-converter",name:"HEX / RGB / HSL",cat:"data",blurb:"Convert colours three ways with a live preview.",tags:["COLOUR","CLIENT-SIDE"],ready:true},
  {slug:"password-generator",name:"Password Generator",cat:"data",blurb:"Strong random passwords from crypto.getRandomValues.",tags:["SECURITY","CRYPTO"],ready:true},
  {slug:"qr-generator",name:"QR Code Generator",cat:"web",blurb:"Generate QR codes for links, text or Wi-Fi.",tags:["QR","CLIENT-SIDE"],ready:true},
  {slug:"ip-inspector",name:"IP & UA Inspector",cat:"web",blurb:"Your public IP, user agent and screen facts.",tags:["NETWORK","CLIENT-SIDE"],ready:true},
  {slug:"markdown-preview",name:"Markdown Previewer",cat:"data",blurb:"Live Markdown preview rendered in the browser.",tags:["MARKDOWN"],ready:true},
  {slug:"csv-json",name:"CSV to JSON",cat:"data",blurb:"Convert delimited text and JSON both ways.",tags:["CSV","JSON"],ready:true},
  {slug:"html-entities",name:"HTML Entity Escaper",cat:"data",blurb:"Escape and unescape HTML and XML entities safely.",tags:["HTML","XML"],ready:true},
  {slug:"jwt-debugger",name:"JWT Debugger",cat:"data",blurb:"Decode a JWT header and payload, client-side only.",tags:["JWT"],ready:true},
  {slug:"diff-checker",name:"Diff Checker",cat:"data",blurb:"Compare two blocks of text line by line.",tags:["DIFF"],ready:true},
  {slug:"lorem-ipsum",name:"Lorem Ipsum Generator",cat:"data",blurb:"Placeholder paragraphs, sentences or words.",tags:["TEXT"],ready:true},
  {slug:"regex-tester",name:"Regex Tester",cat:"data",blurb:"Test patterns with live match highlighting.",tags:["REGEX"],ready:true},
  {slug:"sql-formatter",name:"SQL Formatter",cat:"data",blurb:"Reindent SQL queries so they can actually be read.",tags:["SQL"],ready:true},
  {slug:"pdf-viewer",name:"PDF Viewer",cat:"document",blurb:"Open a PDF in the browser and inspect page by page.",tags:["PDF"],ready:true},
  {slug:"image-to-pdf",name:"Image to PDF",cat:"document",blurb:"Combine images into a single PDF, in your order.",tags:["PDF"],ready:true},
  {slug:"pdf-splitter",name:"PDF Splitter",cat:"document",blurb:"Extract or drop pages and download the result.",tags:["PDF"],ready:true},
  {slug:"pdf-to-text",name:"PDF to Text",cat:"document",blurb:"Pull the text layer out of any PDF.",tags:["PDF"],ready:true},
  {slug:"tts",name:"Browser TTS",cat:"audio",blurb:"Read text aloud with the voices on your device.",tags:["SPEECH"],ready:true},
  {slug:"voice-recorder",name:"Voice Recorder",cat:"audio",blurb:"Record, trim and download clips locally.",tags:["MIC"],ready:true},
  {slug:"voice-changer",name:"Voice Changer",cat:"audio",blurb:"Record or upload audio and change your voice with 12 DSP presets, then save a WAV.",tags:["MIC","EFFECTS","CLIENT-SIDE"],ready:true},
  {slug:"tone-synth",name:"Tone & SFX Synth",cat:"audio",blurb:"Generate tones and effects with the Web Audio API.",tags:["AUDIO"],ready:true},
  {slug:"pitch-speed",name:"Pitch & Speed Changer",cat:"audio",blurb:"Shift pitch and playback rate of any audio file.",tags:["AUDIO"],ready:true},
  {slug:"password-strength",name:"Password Analyser",cat:"data",blurb:"Entropy, crack-time estimates and weakness checks.",tags:["SECURITY"],ready:true},
  {slug:"gradient-maker",name:"CSS Gradient Maker",cat:"design",blurb:"Build linear and radial gradients, copy the CSS.",tags:["CSS"],ready:true},
  {slug:"box-shadow",name:"Box Shadow Generator",cat:"design",blurb:"Layer shadows visually and copy the CSS.",tags:["CSS"],ready:true},
  {slug:"palette",name:"Palette Extractor",cat:"design",blurb:"Pull a palette out of any image you drop in.",tags:["COLOUR"],ready:true},
  {slug:"favicon-generator",name:"Favicon Generator",cat:"design",blurb:"Resize an image to every favicon size and zip it.",tags:["ICONS"],ready:true},
  {slug:"unit-converter",name:"Unit Converter",cat:"math",blurb:"Length, mass, temperature, data and more.",tags:["UNITS"],ready:true},
  {slug:"calculator",name:"Scientific Calculator",cat:"math",blurb:"Full expression evaluation in the browser.",tags:["MATH"],ready:true},
  {slug:"aspect-ratio",name:"Aspect Ratio Calculator",cat:"math",blurb:"Fit widths and heights at any ratio.",tags:["MATH"],ready:true},
  {slug:"loan-calc",name:"Loan & Interest Simulator",cat:"math",blurb:"Compound interest and repayment schedules, charted.",tags:["FINANCE"],ready:true},
  {slug:"bmi",name:"BMI Calculator",cat:"math",blurb:"Body mass index with healthy-range context.",tags:["HEALTH"],ready:true},
  {slug:"gpa",name:"GPA Calculator",cat:"math",blurb:"Semester GPA from your grades and credit units.",tags:["SCHOOL"],ready:true},
  {slug:"meta-tags",name:"Meta Tag Generator",cat:"web",blurb:"Open Graph and Twitter card tags from a form.",tags:["SEO"],ready:true},
  {slug:"http-status",name:"HTTP Status Reference",cat:"web",blurb:"Every status code, searchable, with plain-English notes.",tags:["HTTP"],ready:true},
  {slug:"robots-sitemap",name:"Robots & Sitemap Generator",cat:"web",blurb:"Generate robots.txt and a sitemap skeleton.",tags:["SEO"],ready:true},
  {slug:"flashcards",name:"Flashcards",cat:"study",blurb:"Spaced-repetition decks that live in your browser.",tags:["STUDY"],ready:true},
  {slug:"citation-generator",name:"Citation Generator",cat:"study",blurb:"APA, MLA and Harvard references from a source.",tags:["STUDY"],ready:true},
  {slug:"resume-formatter",name:"Resume Formatter",cat:"study",blurb:"Plain text CV in, styled PDF out.",tags:["CAREER"],ready:true},
  {slug:"typing-speed",name:"Typing Speed Test",cat:"study",blurb:"WPM and accuracy over a timed passage.",tags:["TEST"],ready:true},
  {slug:"pomodoro",name:"Pomodoro Timer",cat:"study",blurb:"Focus sessions with a chime, right in the tab.",tags:["FOCUS"],ready:true},
  {slug:"kanban",name:"Kanban Board",cat:"study",blurb:"Drag-and-drop tasks saved in this browser.",tags:["TASKS"],ready:true},
    {slug:"background-remover",name:"Background Remover",cat:"design",blurb:"Cut the background off a photo in your browser — no upload, no watermark.",tags:["IMAGE","PNG"],ready:true},
    {slug:"element-mixer",name:"Element Mixer",cat:"study",blurb:"All 118 elements — tap two to see the compound they form.",tags:["CHEMISTRY","TABLE"],ready:true},
  {slug:"pdf-to-word",name:"PDF to Word",cat:"document",blurb:"Extract text from any PDF into a Word-compatible .doc download.",tags:["PDF","WORD"],ready:true},
  {slug:"word-to-pdf",name:"Word to PDF",cat:"document",blurb:"Paste text, pick a page size, export a clean paginated PDF.",tags:["PDF","EXPORT"],ready:true},
  {slug:"merge-pdf",name:"Merge PDF",cat:"document",blurb:"Join several PDFs in your chosen order, download one file.",tags:["PDF","MERGE"],ready:true},
  {slug:"split-pdf",name:"Split PDF",cat:"document",blurb:"Split every N pages or by custom ranges, download each part.",tags:["PDF","SPLIT"],ready:true},
  {slug:"organize-pdf",name:"Organise PDF Pages",cat:"document",blurb:"Delete, rotate and reorder pages, then download the result.",tags:["PDF","ROTATE"],ready:true},
  {slug:"compress-pdf",name:"Compress PDF",cat:"document",blurb:"Re-save with object streams and show before/after file size.",tags:["PDF","COMPRESS"],ready:true},
  {slug:"pdf-to-jpg",name:"PDF to JPG",cat:"document",blurb:"Render every page to JPG or PNG, download individually or as a zip.",tags:["PDF","IMAGE","ZIP"],ready:true},
  {slug:"jpg-to-pdf",name:"JPG to PDF",cat:"document",blurb:"Combine JPG, PNG and WebP images into a single paginated PDF.",tags:["PDF","IMAGE"],ready:true},
  {slug:"pdf-rotate",name:"Rotate PDF",cat:"document",blurb:"Rotate all or selected pages with a live thumbnail preview.",tags:["PDF","ROTATE"],ready:true},
  {slug:"pdf-watermark",name:"Watermark PDF",cat:"document",blurb:"Add a diagonal text watermark with colour, opacity and position control.",tags:["PDF","WATERMARK"],ready:true},
  {slug:"pdf-page-numbers",name:"Add Page Numbers",cat:"document",blurb:"Add page numbers in 6 positions with multiple formats including Roman numerals.",tags:["PDF","NUMBERS"],ready:true},
  {slug:"pdf-metadata",name:"PDF Metadata",cat:"document",blurb:"Read, edit and save PDF title, author, subject and keywords.",tags:["PDF","METADATA"],ready:true},
  {slug:"pdf-password-remove",name:"Remove PDF Password",cat:"document",blurb:"Strip the owner password from PDFs you own — no upload, no server.",tags:["PDF","PASSWORD","UNLOCK"],ready:true},
  {slug:"pdf-to-excel",name:"PDF Tables to CSV",cat:"document",blurb:"Pull table-like rows out of any PDF into a downloadable CSV.",tags:["PDF","CSV","EXTRACT"],ready:true},
  {slug:"ocr-image-to-text",name:"Image to Text (OCR)",cat:"document",blurb:"Run Tesseract.js OCR in the browser — no upload, multi-language.",tags:["OCR","TESSERACT","IMAGE"],ready:true},
  {slug:"markdown-to-pdf",name:"Markdown to PDF",cat:"document",blurb:"Write markdown, preview it, export a clean paginated PDF.",tags:["MARKDOWN","PDF","EXPORT"],ready:true},
  {slug:"html-to-pdf",name:"HTML to PDF",cat:"document",blurb:"Paste HTML, preview it live, export a styled PDF.",tags:["HTML","PDF","EXPORT"],ready:true},
  {slug:"pdf-page-extract",name:"Extract PDF Pages",cat:"document",blurb:"Pull a page range into a new PDF with one click.",tags:["PDF","EXTRACT","RANGE"],ready:true},
  {slug:"image-compress",name:"Image Compressor",cat:"design",blurb:"Compression levels with a real similarity-to-original quality readout.",tags:["IMAGE","QUALITY","CLIENT-SIDE"],ready:true},
  {slug:"batch-compressor",name:"Batch Image Compressor",cat:"design",blurb:"Compress many images at once, see the quality loss per file, save as ZIP.",tags:["IMAGE","BATCH","ZIP","CLIENT-SIDE"],ready:true},
  {slug:"image-resize",name:"Image Resizer",cat:"design",blurb:"Resize by pixels or percentage with aspect-ratio lock.",tags:["IMAGE","RESIZE","CLIENT-SIDE"],ready:true},
  {slug:"image-crop",name:"Image Cropper",cat:"design",blurb:"Drag a crop box with fixed ratios and download.",tags:["IMAGE","CROP","CLIENT-SIDE"],ready:true},
  {slug:"image-convert",name:"Image Converter",cat:"design",blurb:"PNG, JPG and WebP via canvas with quality control.",tags:["IMAGE","CONVERT","CLIENT-SIDE"],ready:true},
  {slug:"heic-to-jpg",name:"HEIC to JPG",cat:"design",blurb:"Decode HEIC in-browser via heic2any, no upload.",tags:["HEIC","IMAGE","CLIENT-SIDE"],ready:true},
  {slug:"svg-to-png",name:"SVG to PNG",cat:"design",blurb:"Rasterise an uploaded SVG at your chosen scale.",tags:["SVG","PNG","CLIENT-SIDE"],ready:true},
  {slug:"png-to-jpg",name:"PNG to JPG",cat:"design",blurb:"Flatten transparency onto a chosen background colour.",tags:["PNG","JPG","FLATTEN"],ready:true},
  {slug:"image-to-base64",name:"Image to Base64",cat:"design",blurb:"Convert any image to a Base64 data URI — copy or download.",tags:["IMAGE","BASE64","CLIENT-SIDE"],ready:true},
  {slug:"base64-to-image",name:"Base64 to Image",cat:"design",blurb:"Paste a data URI and preview or download the image.",tags:["IMAGE","BASE64","CLIENT-SIDE"],ready:true},
  {slug:"exif-viewer",name:"EXIF Viewer",cat:"design",blurb:"Read camera EXIF metadata from a JPEG and strip it.",tags:["EXIF","JPEG","METADATA"],ready:true},
  {slug:"image-watermark",name:"Watermark Image",cat:"design",blurb:"Add a text watermark with position, opacity, colour and rotation.",tags:["IMAGE","WATERMARK","CANVAS"],ready:true},
  {slug:"image-rotate",name:"Rotate & Flip",cat:"design",blurb:"Rotate 90/180/270 and flip horizontally or vertically, download.",tags:["IMAGE","ROTATE","FLIP"],ready:true},
  {slug:"image-to-ascii",name:"Image to ASCII",cat:"design",blurb:"Convert any image to ASCII art with adjustable width and ramp.",tags:["IMAGE","ASCII","ART"],ready:true},
  {slug:"favicon-maker",name:"Favicon Maker",cat:"design",blurb:"One image to 16/32/48/180/512 favicons plus a .ico bundle.",tags:["FAVICON","ICO","PNG","CLIENT-SIDE"],ready:true},
  {slug:"image-collage",name:"Collage Maker",cat:"design",blurb:"Arrange images in a grid with custom gap and background, export PNG.",tags:["IMAGE","COLLAGE","GRID","CLIENT-SIDE"],ready:true},
  {slug:"image-to-favicon",name:"SVG to Favicon",cat:"design",blurb:"Rasterise an SVG at every favicon size and generate the link tags.",tags:["SVG","FAVICON","ICO","CLIENT-SIDE"],ready:true},
  {slug:"remove-line-breaks",name:"Remove Line Breaks",cat:"data",blurb:"Strip unwanted newlines, optionally merge paragraphs.",tags:["TEXT","LINE BREAKS","CLEANUP","CLIENT-SIDE"],ready:true},
  {slug:"remove-duplicate-lines",name:"Remove Duplicate Lines",cat:"data",blurb:"Dedupe lines with case and whitespace options, keep order.",tags:["TEXT","DEDUPE","LINES","CLIENT-SIDE"],ready:true},
  {slug:"remove-extra-spaces",name:"Remove Extra Spaces",cat:"data",blurb:"Collapse runs of spaces and tabs, trim each line.",tags:["TEXT","SPACES","CLEANUP","CLIENT-SIDE"],ready:true},
  {slug:"sort-lines",name:"Sort Lines",cat:"data",blurb:"Sort A-Z, Z-A, numeric, by length or shuffle — with dedupe.",tags:["TEXT","SORT","DEDUPE","CLIENT-SIDE"],ready:true},
  {slug:"text-diff",name:"Text Diff",cat:"data",blurb:"Compare two blocks of text line by line with colour highlighting.",tags:["DIFF","COMPARE","LCS","CLIENT-SIDE"],ready:true},
  {slug:"find-replace",name:"Find & Replace",cat:"data",blurb:"Plain or regex find-and-replace with live count.",tags:["TEXT","REGEX","REPLACE","CLIENT-SIDE"],ready:true},
  {slug:"text-stats",name:"Text Statistics",cat:"data",blurb:"Chars, words, sentences, reading time and character frequency.",tags:["TEXT","STATS","FREQUENCY","CLIENT-SIDE"],ready:true},
  {slug:"readability",name:"Readability Score",cat:"data",blurb:"Flesch, Flesch-Kincaid, Gunning Fog, SMOG and ARI scores.",tags:["READABILITY","FLESCH","FOG","SMOG","CLIENT-SIDE"],ready:true},
  {slug:"slugify",name:"Slug Generator",cat:"data",blurb:"SEO-friendly URL slugs with separator and diacritic options.",tags:["SLUG","SEO","URL","CLIENT-SIDE"],ready:true},
  {slug:"reverse-text",name:"Reverse Text",cat:"data",blurb:"Reverse characters, word order or line order in one click.",tags:["TEXT","REVERSE","CLIENT-SIDE"],ready:true},
  {slug:"add-line-numbers",name:"Add Line Numbers",cat:"data",blurb:"Prefix each line with a configurable number, padding and separator.",tags:["TEXT","LINES","NUMBERING","CLIENT-SIDE"],ready:true},
  {slug:"text-to-emoji",name:"Text to Emoji",cat:"data",blurb:"Convert letters to regional flags, bold, monospace or squared emoji.",tags:["TEXT","EMOJI","UNICODE","CLIENT-SIDE"],ready:true},
  {slug:"zalgo",name:"Zalgo Text",cat:"data",blurb:"Corrupt text with combining diacritical marks at adjustable intensity.",tags:["TEXT","ZALGO","UNICODE","CLIENT-SIDE"],ready:true},
  {slug:"morse-code",name:"Morse Code",cat:"data",blurb:"Translate text to Morse and back with audio playback.",tags:["MORSE","AUDIO","ENCODE","DECODE","CLIENT-SIDE"],ready:true},
  {slug:"title-case",name:"Title Case Converter",cat:"data",blurb:"Title, AP, Chicago, sentence, camel, snake and kebab in one tool.",tags:["TEXT","TITLE CASE","AP","CHICAGO","CLIENT-SIDE"],ready:true},
  {slug:"strip-html",name:"Strip HTML",cat:"data",blurb:"Remove all HTML tags and decode entities to plain text.",tags:["HTML","STRIP","TEXT","CLIENT-SIDE"],ready:true},
  {slug:"text-to-html",name:"Text to HTML",cat:"data",blurb:"Convert plain text to HTML paragraphs with escaping and headings.",tags:["TEXT","HTML","CONVERT","CLIENT-SIDE"],ready:true},
  {slug:"json-to-yaml",name:"JSON to YAML",cat:"data",blurb:"Convert JSON objects to clean YAML, client-side.",tags:["JSON","YAML","CONVERT","CLIENT-SIDE"],ready:true},
  {slug:"yaml-to-json",name:"YAML to JSON",cat:"data",blurb:"Parse YAML and export formatted JSON.",tags:["YAML","JSON","CONVERT","CLIENT-SIDE"],ready:true},
  {slug:"json-to-csv",name:"JSON to CSV",cat:"data",blurb:"Flatten a JSON array into CSV with headers and download.",tags:["JSON","CSV","CONVERT","CLIENT-SIDE"],ready:true},
  {slug:"xml-formatter",name:"XML Formatter",cat:"data",blurb:"Prettify or minify XML with validation and indentation control.",tags:["XML","FORMAT","PRETTIFY","CLIENT-SIDE"],ready:true},
  {slug:"html-formatter",name:"HTML Formatter",cat:"data",blurb:"Prettify or minify HTML with indentation control.",tags:["HTML","FORMAT","PRETTIFY","CLIENT-SIDE"],ready:true},
  {slug:"css-formatter",name:"CSS Formatter",cat:"data",blurb:"Prettify or minify CSS with indentation control.",tags:["CSS","FORMAT","PRETTIFY","CLIENT-SIDE"],ready:true},
  {slug:"js-formatter",name:"JS Formatter",cat:"data",blurb:"Prettify or minify JavaScript with indentation control.",tags:["JS","FORMAT","PRETTIFY","CLIENT-SIDE"],ready:true},
  {slug:"css-minifier",name:"CSS Minifier",cat:"data",blurb:"Minify CSS with before/after byte count and download.",tags:["CSS","MINIFY","CLIENT-SIDE"],ready:true},
  {slug:"html-minifier",name:"HTML Minifier",cat:"data",blurb:"Minify HTML with comment control and byte savings.",tags:["HTML","MINIFY","CLIENT-SIDE"],ready:true},
  {slug:"utm-builder",name:"UTM Builder",cat:"data",blurb:"Build UTM tracking URLs with live preview and shortener.",tags:["UTM","URL","MARKETING","CLIENT-SIDE"],ready:true},
  {slug:"cron-builder",name:"Cron Builder",cat:"data",blurb:"Build cron expressions from dropdowns with plain-English descriptions.",tags:["CRON","SCHEDULE","CLIENT-SIDE"],ready:true},
  {slug:"mime-types",name:"MIME Types",cat:"data",blurb:"Look up any file extension to its MIME type and back.",tags:["MIME","FILE","CLIENT-SIDE"],ready:true},
  {slug:"user-agent-parser",name:"User Agent Parser",cat:"data",blurb:"Parse a UA string into browser, OS, engine and device.",tags:["UA","BROWSER","CLIENT-SIDE"],ready:true},
  {slug:"url-parser",name:"URL Parser",cat:"data",blurb:"Break any URL into protocol, host, port, path, query and hash.",tags:["URL","PARSE","CLIENT-SIDE"],ready:true},
  {slug:"qr-scanner",name:"QR Scanner",cat:"data",blurb:"Decode QR codes from a camera or uploaded image.",tags:["QR","CAMERA","CLIENT-SIDE"],ready:true},
  {slug:"barcode-gen",name:"Barcode Generator",cat:"data",blurb:"Generate CODE128, EAN, UPC and more barcodes as PNG.",tags:["BARCODE","CODE128","EAN","CLIENT-SIDE"],ready:true},
  {slug:"humanizer",name:"Humanizer",cat:"text",blurb:"Spot the AI tells in a draft and auto-fix the safe ones. Scores human-likeness.",tags:["WRITING","AI-TELLS","CLIENT-SIDE"],ready:true},
  {slug:"prompt-compiler",name:"AI Prompt Compiler",cat:"text",blurb:"Turn a rough ask into a structured prompt with role, task, format, length and rules.",tags:["PROMPT","WRITING","CLIENT-SIDE"],ready:true},
  {slug:"sentence-corrector",name:"Sentence Corrector",cat:"text",blurb:"Capitals, spacing, common misspellings, a/an and missing full stops - with a change log.",tags:["GRAMMAR","CLIENT-SIDE"],ready:true},
  {slug:"png-to-webp",name:"PNG to WEBP",cat:"design",blurb:"Convert PNG or JPG to WEBP and see exactly how much smaller the file gets.",tags:["IMAGE","WEBP","CLIENT-SIDE"],ready:true},
  {slug:"webp-to-png",name:"WEBP to PNG",cat:"design",blurb:"Turn any WEBP image back into a standard PNG, ready to use anywhere.",tags:["IMAGE","PNG","CLIENT-SIDE"],ready:true},
  {slug:"percentage-calculator",name:"Percentage Calculator",cat:"math",blurb:"Percent of a number, what percent one number is of another, and percentage change.",tags:["MATH","PERCENT","CLIENT-SIDE"],ready:true},
  {slug:"age-calculator",name:"Age Calculator",cat:"math",blurb:"Exact age in years, months, weeks, days and hours, plus the countdown to the next birthday.",tags:["MATH","DATE","CLIENT-SIDE"],ready:true},
  {slug:"date-difference",name:"Date Difference",cat:"math",blurb:"Days between two dates, broken down into weeks, months, years and working days.",tags:["MATH","DATE","CLIENT-SIDE"],ready:true},
  {slug:"tip-calculator",name:"Tip Calculator",cat:"math",blurb:"Work out the tip, the total and what each person owes when you split the bill.",tags:["MATH","MONEY","CLIENT-SIDE"],ready:true},
  {slug:"discount-calculator",name:"Discount Calculator",cat:"math",blurb:"Apply one or two stacked discounts and see the final price and what you saved.",tags:["MATH","MONEY","CLIENT-SIDE"],ready:true},
  {slug:"compound-interest",name:"Compound Interest",cat:"math",blurb:"Project savings or investments forward with optional monthly deposits.",tags:["MATH","MONEY","CLIENT-SIDE"],ready:true},
  {slug:"timezone-converter",name:"Time Zone Converter",cat:"web",blurb:"Convert a date and time between any two time zones, including daylight saving.",tags:["TIME","ZONES","CLIENT-SIDE"],ready:true},
  {slug:"coin-flip",name:"Coin Flip",cat:"math",blurb:"Flip up to 500 coins at once and get the heads and tails tally.",tags:["RANDOM","FLIP","CLIENT-SIDE"],ready:true},
  {slug:"frequency-generator",name:"Frequency Generator",cat:"audio",blurb:"Play any frequency from 1 Hz to 22 kHz, pick a waveform, run a sweep and see the wave live.",tags:["AUDIO","TONE","HZ","CLIENT-SIDE"],ready:true},
  {slug:"contrast-checker",name:"Contrast Checker",cat:"design",blurb:"Check any two colours against the WCAG contrast rules and see which levels pass.",tags:["WCAG","ACCESSIBILITY","COLOUR","CLIENT-SIDE"],ready:true},
  {slug:"caesar-cipher",name:"Caesar Cipher",cat:"data",blurb:"Shift text through the alphabet, run ROT13 or brute-force every one of the 25 keys.",tags:["CIPHER","ROT13","TEXT","CLIENT-SIDE"],ready:true},
  {slug:"dice-roller",name:"Dice Roller",cat:"math",blurb:"Roll up to 500 dice of any size, with a modifier and a full tally of the results.",tags:["RANDOM","DICE","RPG","CLIENT-SIDE"],ready:true},
  {slug:"markdown-table-generator",name:"Markdown Table Generator",cat:"data",blurb:"Paste CSV, TSV or pipe data and get a clean Markdown table with alignment options.",tags:["MARKDOWN","TABLE","CSV","CLIENT-SIDE"],ready:true},
  {slug:"vtt-to-srt",name:"VTT to SRT",cat:"data",blurb:"Convert WebVTT subtitles into SRT, with an optional timing shift and a .srt download.",tags:["SUBTITLES","VTT","SRT","CLIENT-SIDE"],ready:true},
  {slug:"invoice-generator",name:"Invoice Generator",cat:"document",blurb:"Build a tax invoice with line items, discount and tax, then print or save it as PDF.",tags:["INVOICE","BILLING","TAX","CLIENT-SIDE"],ready:true},
  {slug:"csv-to-json",name:"CSV to JSON",cat:"data",blurb:"Turn CSV or TSV into clean JSON, correctly handling quoted fields, escaped quotes and blank lines.",tags:["CSV","JSON","CONVERT","CLIENT-SIDE"],ready:true},
  {slug:"jwt-decoder",name:"JWT Decoder",cat:"data",blurb:"Decode a JWT into its header, payload and claims timeline, and see at a glance whether it has expired.",tags:["JWT","BASE64","AUTH","CLIENT-SIDE"],ready:true},
  {slug:"css-border-radius-generator",name:"Border Radius Generator",cat:"design",blurb:"Dial in all eight corner radii, watch the shape change and copy the exact CSS.",tags:["CSS","SHAPE","DESIGN","CLIENT-SIDE"],ready:true},
  {slug:"gradient-text-generator",name:"Gradient Text Generator",cat:"design",blurb:"Build linear, radial or conic gradient text and copy the CSS or the ready-made HTML span.",tags:["CSS","GRADIENT","TYPE","CLIENT-SIDE"],ready:true},
  {slug:"timestamp-diff",name:"Timestamp Difference",cat:"math",blurb:"Difference between two Unix timestamps or dates, broken down into days, hours, weeks and years.",tags:["UNIX","TIME","DIFF","CLIENT-SIDE"],ready:true},
  {slug:"braille-translator",name:"Braille Translator",cat:"text",blurb:"Convert text to Grade 1 Unicode Braille and back, with capital and number signs handled properly.",tags:["BRAILLE","ACCESSIBILITY","TEXT","CLIENT-SIDE"],ready:true},
  {slug:"spin-wheel",name:"Spin Wheel",cat:"math",blurb:"Draw a wheel of any size, spin it with a fair cryptographic pick and land the winner under the pointer.",tags:["RANDOM","WHEEL","PICKER","CLIENT-SIDE"],ready:true},
  {slug:"signature-generator",name:"Signature Generator",cat:"design",blurb:"Draw a signature with mouse, pen or finger and download it as a transparent PNG.",tags:["SIGNATURE","CANVAS","PNG","CLIENT-SIDE"],ready:true},
  {slug:"vigenere-cipher",name:"Vigenere Cipher",cat:"text",blurb:"Encrypt or decrypt with a repeating keyword, keeping case and leaving spaces and punctuation in place.",tags:["CIPHER","VIGENERE","TEXT","CLIENT-SIDE"],ready:true},
  {slug:"base32",name:"Base32 Encoder",cat:"data",blurb:"Encode text to RFC 4648 Base32 and decode it back, with padding control and a byte count.",tags:["BASE32","RFC 4648","ENCODE","CLIENT-SIDE"],ready:true},
  {slug:"palindrome-checker",name:"Palindrome Checker",cat:"text",blurb:"Check any phrase as a palindrome, ignoring case, accents and punctuation, and see the first mismatch.",tags:["PALINDROME","TEXT","LIVE","CLIENT-SIDE"],ready:true},
  {slug:"css-clip-path-generator",name:"CSS Clip Path Generator",cat:"design",blurb:"Pick a shape or drag the points, then copy the exact clip-path polygon CSS.",tags:["CSS","CLIP-PATH","SHAPE","CLIENT-SIDE"],ready:true},
  {slug:"random-number",name:"Random Number Generator",cat:"math",blurb:"Draw random whole numbers in any range, with unique and sorted modes and a cryptographic source.",tags:["RANDOM","CRYPTO","UNIQUE","CLIENT-SIDE"],ready:true},
  {slug:"roman-numerals",name:"Roman Numeral Converter",cat:"math",blurb:"Convert 1-3999 both ways, see how each numeral adds up and catch non-standard forms like IIII.",tags:["ROMAN","NUMBERS","LIVE","CLIENT-SIDE"],ready:true},
  {slug:"prime-checker",name:"Prime Checker & Factoriser",cat:"math",blurb:"Test any number for primality with Miller-Rabin, then get its prime factorisation and every divisor.",tags:["PRIME","FACTORS","MILLER-RABIN","CLIENT-SIDE"],ready:true},
  {slug:"statistics-calculator",name:"Statistics Calculator",cat:"math",blurb:"Mean, median, mode, quartiles, range and standard deviation for any list of numbers.",tags:["MEAN","MEDIAN","STD DEV","CLIENT-SIDE"],ready:true},
  {slug:"vat-calc",name:"VAT & GST Calculator",cat:"math",blurb:"Add tax to a net amount or strip it back out of a gross amount, with common rates one click away.",tags:["VAT","GST","TAX","CLIENT-SIDE"],ready:true},
  {slug:"css-shadow",name:"CSS Box Shadow Builder",cat:"design",blurb:"Layer up to three shadows with x, y, blur, spread, opacity and inset, then copy the CSS.",tags:["CSS","SHADOW","LIVE","CLIENT-SIDE"],ready:true},
  {slug:"cubic-bezier",name:"Cubic Bezier Editor",cat:"design",blurb:"Drag the two control points on a curve, watch the easing play and copy the cubic-bezier CSS.",tags:["CSS","EASING","CANVAS","CLIENT-SIDE"],ready:true},
  {slug:"stopwatch",name:"Stopwatch",cat:"study",blurb:"Millisecond stopwatch with lap splits, fastest lap and keyboard start/stop.",tags:["TIMER","LAPS","PRECISION","CLIENT-SIDE"],ready:true},
  {slug:"meta-tag-generator",name:"Meta Tag Generator",cat:"web",blurb:"Open Graph and Twitter card tags with a live link preview and character counters.",tags:["OPEN GRAPH","TWITTER","SEO","CLIENT-SIDE"],ready:true},
  {slug:"duplicate-line-remover",name:"Duplicate Line Remover",cat:"text",blurb:"Strip repeated lines, keep first or last, case-fold, trim and sort the result.",tags:["DEDUPE","CLEANUP","LINES","CLIENT-SIDE"],ready:true},
  {slug:"cron-parser",name:"Cron Expression Parser",cat:"web",blurb:"Expand a crontab into its fields, plain English and the next real run times.",tags:["CRON","SCHEDULER","CRONTAB","CLIENT-SIDE"],ready:true},
  {slug:"hex-to-rgb",name:"HEX to RGB Converter",cat:"design",blurb:"Convert HEX, RGB, HSL and HSV with WCAG contrast ratios and a full tint scale.",tags:["COLOUR","HEX","HSL","CLIENT-SIDE"],ready:true},
  {slug:"anagram-solver",name:"Anagram Solver",cat:"text",blurb:"Find exact anagrams and longer words you can build from a letter set.",tags:["WORDS","ANAGRAM","PUZZLE","CLIENT-SIDE"],ready:true},
  {slug:"screen-resolution",name:"Screen Resolution & Viewport",cat:"web",blurb:"Read the live viewport, DPR and orientation, and see which CSS breakpoints are active.",tags:["VIEWPORT","BREAKPOINTS","DISPLAY","CLIENT-SIDE"],ready:true},
  {slug:"csv-to-yaml",name:"CSV to YAML",cat:"data",blurb:"Turn a CSV table into clean YAML with typed scalars, quoted strings and a list of maps.",tags:["CSV","YAML","TYPED","CLIENT-SIDE"],ready:true},
  {slug:"json-minifier",name:"JSON Minifier & Formatter",cat:"data",blurb:"Strip JSON whitespace or pretty-print it, with key sort and duplicate detection.",tags:["JSON","MINIFY","FORMAT","CLIENT-SIDE"],ready:true},
  {slug:"json-schema-gen",name:"JSON Schema Generator",cat:"data",blurb:"Infer a draft 2020-12 JSON Schema from a sample document, with types and required keys.",tags:["SCHEMA","INFER","DRAFT","CLIENT-SIDE"],ready:true},
  {slug:"jwt-inspector",name:"JWT Inspector",cat:"data",blurb:"Decode a JSON Web Token, list its claims on a timeline and flag expiry.",tags:["JWT","CLAIMS","EXPIRY","CLIENT-SIDE"],ready:true},
];