// WEBSITES — one line per entry
const CATS = {"marketplace": "MARKETPLACE", "portfolio": "PORTFOLIO", "media": "MEDIA & CONTENT", "fun": "FUN WEBSITES"};
const RAW = [
  {slug:"wearbenin",name:"WearBenin",cat:"marketplace",url:"https://smuglepug.github.io/wearbenin-site",blurb:"Benin clothing marketplace — browse and buy authentic pieces.",tags:["E-COMMERCE","FASHION"],ready:true},
  {slug:"rentify",name:"Rentify Events",cat:"marketplace",url:"https://rentifyevents.com",blurb:"Event marketplace for Benin City — find venues, decor, catering and MCs in one place.",tags:["EVENTS","MARKETPLACE"],cover:"/workspace/covers/rentify.jpg",ready:true},
  {slug:"toolstack",name:"Toolstack Labs",cat:"media",url:"https://www.youtube.com/@ToolstackLabs",blurb:"Tech explainer channel — tools and tech, explained simply.",tags:["YOUTUBE","TECH"],cover:"/workspace/covers/toolstack.jpg",ready:true},
  {slug:"jobhub",name:"JobHub",cat:"portfolio",url:"#",blurb:"Job board and hiring platform.",tags:["JOBS","MARKETPLACE"],ready:false},
  {slug:"portfolio",name:"Owen Osayi — The Founder",cat:"portfolio",url:"/",blurb:"This site. Engineering, design and algorithmic thinking, unified.",tags:["PORTFOLIO","PERSONAL"],ready:true},
  {slug:"neal-fun",name:"Neal.fun",cat:"fun",url:"https://neal.fun",blurb:"Small, strange, addictive browser games. The reason half this site's games exist.",tags:["GAMES","FUN"],cover:"/workspace/covers/neal-fun.jpg",ready:true},
  {slug:"the-pudding",name:"The Pudding",cat:"fun",url:"https://pudding.cool",blurb:"Data stories that actually respect you. The gold standard for explainers.",tags:["DATA","STORIES"],cover:"/workspace/covers/the-pudding.jpg",ready:true},
  {slug:"wonderland",name:"Wonderland",cat:"fun",url:"https://www.wonderlandengine.com",blurb:"Build 3D scenes in the browser and walk around them. No install, no account.",tags:["3D","CREATE"],cover:"/workspace/covers/wonderland.jpg",ready:true},
  {slug:"patatap",name:"Patatap",cat:"fun",url:"https://patatap.com",blurb:"Every key and click makes a sound and a shape. Deeply simple, endlessly good.",tags:["SOUND","PLAY"],ready:true},
  {slug:"radio-garden",name:"Radio Garden",cat:"fun",url:"https://radio.garden",blurb:"Spin a globe and listen to live radio from any city on earth.",tags:["MUSIC","MAP"],cover:"/workspace/covers/radio-garden.jpg",ready:true},
  {slug:"window-swap",name:"Window Swap",cat:"fun",url:"https://window-swap.com",blurb:"Teleport into a stranger's window for five minutes. Still works. Somehow.",tags:["STRANGE","PEOPLE"],cover:"/workspace/covers/window-swap.jpg",ready:true},
  {slug:"zoomquilt",name:"Zoomquilt",cat:"fun",url:"https://zoomquilt.org",blurb:"An endless zoom that keeps revealing more detail. The original, still unbeaten.",tags:["ZOOM","INFINITE"],cover:"/workspace/covers/zoomquilt.jpg",ready:true},
  {slug:"thispersondoesnotexist",name:"This Person Does Not Exist",cat:"fun",url:"https://thispersondoesnotexist.com",blurb:"Photoreal faces of people who do not exist, generated fresh on every reload.",tags:["AI","FACES"],ready:true},
  {slug:"find-the-invisible-cow",name:"Find The Invisible Cow",cat:"fun",url:"https://findtheinvisiblecow.com",blurb:"Spot the one letter that differs from the rest. As deceptively simple as it looks.",tags:["MYSTERY","ARCADE"],ready:true},
  {slug:"mapcrunch",name:"MapCrunch",cat:"fun",url:"https://www.mapcrunch.com/",blurb:"Drop anywhere on the world and land in the street view of that exact spot.",tags:["MAP","GEOGRAPHY"],ready:true},
  {slug:"the-useless-web",name:"The Useless Web",cat:"fun",url:"https://theuselessweb.com/",blurb:"A button that only leads to more useless buttons. The internet, distilled.",tags:["ABSURD","FUN"],ready:true},
  {slug:"hacker-typer",name:"Hacker Typer",cat:"fun",url:"https://hackertyper.net/",blurb:"Touch-typing drill against real snippets of code.",tags:["TYPING","DEV"],ready:true},
  {slug:"pointer-pointer",name:"Pointer Pointer",cat:"fun",url:"https://pointerpointer.com/",blurb:"Tries to find a point on screen that is pointing at a point on screen.",tags:["POINTER","WEIRD"],ready:true},
  {slug:"staggering-beauty",name:"Staggering Beauty",cat:"fun",url:"https://staggeringbeauty.com/",blurb:"The same 300 photographs in a new arrangement, over and over.",tags:["PHOTO","GENERATIVE"],ready:true},
  {slug:"scream-into-the-void",name:"Scream Into The Void",cat:"fun",url:"https://screamintothevoid.com/",blurb:"Your scream is thrown into space as a message. Nothing is sent.",tags:["SOUND","ABSURD"],ready:true},
  {slug:"wordle",name:"Word Guess",cat:"fun",url:"https://www.nytimes.com/games/wordle/index.html",blurb:"Six tries, five letters, one shared daily answer.",tags:["WORDS","PUZZLE"],ready:true},
  {slug:"duo-trigordle",name:"Duotrigordle",cat:"fun",url:"https://duotrigordle.com/",blurb:"Three boards, two guesses. The sequel people asked for after Wordle.",tags:["WORDS","PUZZLE"],ready:true},
  {slug:"stellarium",name:"Stellarium Web",cat:"fun",url:"https://stellarium-web.org/",blurb:"A planetarium in the browser. Point it at the sky and look up.",tags:["SPACE","EDUCATION"],ready:true},
  {slug:"shut-up-and-take-my-money",name:"Shut Up And Take My Money",cat:"fun",url:"https://shutupandtakemymoney.com/",blurb:"Watches real prices and rings when something you want hits the number you said.",tags:["SHOPPING","ALERTS"],ready:true},
  {slug:"paper-toilet",name:"Paper Toilet",cat:"fun",url:"https://papertoilet.com/",blurb:"A browser game that plays out a very long, very slow plot.",tags:["ABSURD","COMIC"],ready:true},
  {slug:"drive-me-insane",name:"Drive Me Insane",cat:"fun",url:"https://drivemeinsane.com/",blurb:"Read the plate, pick the matching country. Deeply trivial.",tags:["TRIVIA","GEOGRAPHY"],ready:true},
  {slug:"muscle-wiki",name:"MuscleWiki",cat:"fun",url:"https://musclewiki.com/",blurb:"Every muscle in the body, with an animation and where to find it in yourself.",tags:["HEALTH","REFERENCE"],ready:true},
  {slug:"internet-live-stats",name:"Internet Live Stats",cat:"fun",url:"https://www.internetlivestats.com/",blurb:"How much of the internet is happening right now, updating live.",tags:["DATA","NETWORK"],ready:true},
  {slug:"this-is-sand",name:"This Is Sand",cat:"fun",url:"https://thisissand.com/",blurb:"A bowl of sand that never runs out and never spills.",tags:["SAND","CALM"],ready:true},
  {slug:"lizard-point",name:"Lizard Point",cat:"fun",url:"https://lizardpoint.com/",blurb:"World flags at full speed. Brutal, and very hard to put down.",tags:["FLAGS","QUIZ"],ready:true},
  {slug:"music-theory",name:"musictheory.net",cat:"fun",url:"https://www.musictheory.net/",blurb:"Lessons, trainers and a piano that listens as you play.",tags:["MUSIC","LEARNING"],ready:true},
  {slug:"radio-oooo",name:"Radiooooo",cat:"fun",url:"https://app.radiooooo.com/",blurb:"Hundreds of stations at once. Pick a decade and drown in it.",tags:["RADIO","SOUND"],ready:true},
  {slug:"sleepy-time",name:"Sleepy Time Calculator",cat:"fun",url:"https://sleepopolis.com/calculators/sleep/",blurb:"Works out when you should sleep, or when to stop sleeping.",tags:["SLEEP","HEALTH"],ready:true},
  {slug:"29a.ch",name:"29a.ch",cat:"fun",url:"https://29a.ch/",blurb:"A small personal site of tiny interactive toys, and quietly brilliant.",tags:["EXPERIMENT","TOYS"],ready:true},
  {slug:"explore-livecams",name:"Explore.org Live Cams",cat:"fun",url:"https://explore.org/livecams/",blurb:"Live wildlife cameras. Mostly you wait, and then something happens.",tags:["NATURE","CALM"],ready:true},
  {slug:"my-fridge-food",name:"My Fridge Food",cat:"fun",url:"https://www.myfridgefood.com/",blurb:"Opens a chain of possible recipes from whatever is in your fridge.",tags:["COOKING","RECIPES"],ready:true},
  {slug:"omfg-dogs",name:"OMFG Dogs",cat:"fun",url:"https://www.omfgdogs.com/",blurb:"Dogs, categorised by mood. More useful than it has any right to be.",tags:["DOGS","FUN"],ready:true},
  {slug:"weave-silk",name:"Weavesilk",cat:"fun",url:"https://weavesilk.com/",blurb:"An interactive generative weave you paint with light.",tags:["ART","GENERATIVE"],ready:true},
  {slug:"conspiracy-theories",name:"Conspiracy Theories",cat:"fun",url:"https://en.wikipedia.org/wiki/List_of_conspiracy_theories",blurb:"A Wikipedia list of conspiracy theories. Pick one and fall down it for an hour.",tags:["READING","RABBIT HOLE"],ready:true},
  {slug:"pokemon-showdown",name:"Pokemon Showdown",cat:"fun",url:"https://pokemonshowdown.com/",blurb:"Competitive Pokemon in the browser, with replays and tier lists.",tags:["GAMES","STRATEGY"],ready:true},
  {slug:"sporcle",name:"Sporcle",cat:"fun",url:"https://www.sporcle.com/",blurb:"Daily quizzes on an absurd range of subjects.",tags:["QUIZ","TRIVIA"],ready:true},
  {slug:"cookie-clicker",name:"Cookie Clicker",cat:"fun",url:"https://orteil.dashnet.org/cookieclicker/",blurb:"The idle game that invented the genre. Click a cookie, make a factory.",tags:["IDLE","CLICKER"],ready:true},
  {slug:"habitica",name:"Habitica",cat:"fun",url:"https://habitica.com/",blurb:"Turns your to-do list into an RPG where slacking costs you health.",tags:["HABITS","RPG"],ready:true},
  {slug:"letters-of-note",name:"Letters of Note",cat:"fun",url:"https://news.lettersofnote.com/",blurb:"Long-form letters from people worth reading. Genuinely moving.",tags:["WRITING","LONGREAD"],ready:true},
  {slug:"atlas-obscura",name:"Atlas Obscura",cat:"fun",url:"https://www.atlasobscura.com/",blurb:"The world's strangest places, one entry at a time.",tags:["PLACES","CURIOSITY"],ready:true},
  {slug:"foddy-athletics",name:"Foddy Athletics",cat:"fun",url:"https://www.foddy.net/legacy/Athletics.html",blurb:"One-button athletics, decades old, still the best one-button game ever.",tags:["ARCADE","RETRO"],ready:true},
  {slug:"flash-by-night",name:"Flash By Night",cat:"fun",url:"https://flashbynight.com/",blurb:"Flash games preserved and playable, long after the format died.",tags:["FLASH","RETRO"],ready:true},
  {slug:"xkcd",name:"xkcd",cat:"fun",url:"https://xkcd.com/",blurb:"The webcomic. Alt text is the best part.",tags:["COMIC","HUMOUR"],ready:true},
  {slug:"you-are-listening-to",name:"You Are Listening To",cat:"fun",url:"https://youarelistening.to/",blurb:"A named music station that slowly shifts genre. All one channel.",tags:["RADIO","AMBIENT"],ready:true},
  {slug:"incredibox",name:"Incredibox",cat:"fun",url:"https://www.incredibox.com/",blurb:"Drag sound blocks into a loop. A band you assemble out of genre.",tags:["MUSIC","PLAY"],ready:true},
  {slug:"a-soft-murmur",name:"A Soft Murmur",cat:"fun",url:"https://asoftmurmur.com/",blurb:"Type a word, get a cloud made of it. Weighted for exactly long enough.",tags:["AMBIENT","CALM"],ready:true},
  {slug:"rainy-mood",name:"Rainy Mood",cat:"fun",url:"https://rainymood.com/",blurb:"Rain on a window, or thunder, or a cafe, or a train, on a timer.",tags:["AMBIENT","FOCUS"],ready:true},
  {slug:"quick-draw",name:"Quick, Draw!",cat:"fun",url:"https://quickdraw.withgoogle.com/",blurb:"Twenty seconds to draw something, a neural network guesses. It is often right.",tags:["AI","DRAWING"],ready:true},
  {slug:"da-font",name:"DaFont",cat:"fun",url:"https://www.dafont.com/",blurb:"An enormous archive of free fonts.",tags:["FONTS","DESIGN"],ready:true},
  {slug:"space-jam",name:"Space Jam",cat:"fun",url:"https://www.spacejam.com/",blurb:"The original 1996 site, preserved exactly as it was.",tags:["RETRO","NOSTALGIA"],ready:true},
  {slug:"letters-live",name:"Live From Letters",cat:"fun",url:"https://news.lettersofnote.com/",blurb:"A live feed of letters worth reading, archived and searchable.",tags:["WRITING","ARCHIVE"],ready:true},
  {slug:"snopes",name:"Snopes",cat:"fun",url:"https://www.snopes.com/",blurb:"Fact-checks every rumour that circulates. The best instinct on the internet.",tags:["FACTS","SOURCING"],ready:true},
  {slug:"the-onion",name:"The Onion",cat:"fun",url:"https://theonion.com/",blurb:"Satire so good people mistake it for reporting.",tags:["HUMOUR","SATIRE"],ready:true},
  {slug:"lifehacker",name:"Lifehacker",cat:"fun",url:"https://lifehacker.com/",blurb:"Tips for getting a slightly better life out of the one you have.",tags:["LIFE","TIPS"],ready:true},
  {slug:"mix-com",name:"Mix.com",cat:"fun",url:"https://mix.com/",blurb:"Pick a genre, get a playlist, do not touch it for three hours.",tags:["MUSIC","PLAY"],ready:true},
  {slug:"lego-videos",name:"LEGO Kids Videos",cat:"fun",url:"https://kids.lego.com/en-us/videos",blurb:"An archive of every LEGO kids' video, in order.",tags:["VIDEO","NOSTALGIA"],ready:true},
  {slug:"instructables",name:"Instructables",cat:"fun",url:"https://www.instructables.com/",blurb:"Step-by-step guides to making almost anything. The web's how-to manual.",tags:["MAKING","DIY"],ready:true},
  {slug:"internet-archive",name:"Internet Archive",cat:"fun",url:"https://web.archive.org/",blurb:"The whole web, archived. A time machine you can actually drive.",tags:["ARCHIVE","RESEARCH"],ready:true},
  {slug:"addictivetips",name:"AddictiveTips",cat:"fun",url:"https://www.addictivetips.com/",blurb:"Long-form guides to the games and software you already play.",tags:["GAMES","GUIDES"],ready:true},
  {slug:"this-is-colossal",name:"Colossal",cat:"fun",url:"https://www.thisiscolossal.com/",blurb:"The best science, nature and design writing on the internet, collected.",tags:["READING","CURIOSITY"],ready:true},
  {slug:"individual-dogs",name:"A List Of Every Individual Dog",cat:"fun",url:"https://en.wikipedia.org/wiki/List_of_individual_dogs",blurb:"Wikipedia's list of every dog with a Wikipedia page. Deeply strange and moving.",tags:["READING","RABBIT HOLE"],ready:true},
  {slug:"apollo-11-today",name:"What Would It Be Like On The Moon",cat:"fun",url:"https://apod.nasa.gov/apod/astropix.html",blurb:"Astronomy Picture of the Day. A new photograph of space, every day.",tags:["SPACE","PHOTO"],ready:true},
  {slug:"cursed",name:"The Cursed Video Archive",cat:"fun",url:"https://www.youtube.com/@CodyKo",blurb:"Early-internet weirdness, preserved. Do not watch at 3am.",tags:["WEIRD","YOUTUBE"],ready:true}
];
